site_name: HaramConf 2024 H2
site_url: https://fannyrancourt.github.io/haramconf
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

theme:
  name: material 
  language: fr
  palette:
    accent: red
  logo: assets/HaramConf.png
  favicon: assets/HaramConflogo.png
  icon:
    admonition:
      bug: octicons/info-16
      example: material/alert-decagram
  
